# Generated by Django 5.2.2 on 2025-06-07 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_curtidas',
        ),
        migrations.AddField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='postagens/'),
        ),
    ]
